blueprint:
  name: "门磁控制小爱音箱 + V6 Mesh 开关断电再上电"
  description: "门开关时，小爱音箱播报状态；门关时触发 V6 Mesh 开关断电3秒再来电"
  domain: automation

  input:
    door_sensor:
      name: 门磁传感器
      description: "请选择要监听的门磁传感器"
      selector:
        entity:
          domain: binary_sensor
    speaker:
      name: 小爱音箱
      description: "请选择一个或多个小爱音箱实体"
      selector:
        target:
          entity:
            domain: notify
    mesh_switch:
      name: V6 Mesh 开关
      description: "请选择 V6 Mesh 开关实体（switch）"
      selector:
        entity:
          domain: switch

trigger:
  - platform: state
    entity_id: !input door_sensor
    to:
      - "on"
      - "off"

action:
  - choose:
      # 门打开播报
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: "on"
        sequence:
          - service: notify.send_message
            target: !input speaker
            data:
              message: "门已打开"

      # 门关闭播报 + Mesh 开关断电3秒再来电
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: "off"
        sequence:
          # 播报门已关闭
          - service: notify.send_message
            target: !input speaker
            data:
              message: "门已关闭"
          # 断电
          - service: switch.turn_off
            target:
              entity_id: !input mesh_switch
          # 延时3秒
          - delay:
              seconds: 3
          # 上电
          - service: switch.turn_on
            target:
              entity_id: !input mesh_switch

mode: single
