blueprint:
  name: "民宿节电逻辑（完全零配置，多随意贴兼容版）"
  description: "门关闭触发空调延时，随意贴可保持供电，内置临时状态，无需用户创建 timer 或 input_boolean"
  domain: automation
  input:
    door_sensor:
      name: 门磁
      description: "门磁传感器"
      selector:
        entity:
          domain: binary_sensor
    air_conditioner:
      name: 智能开关（空调）
      description: "控制空调的开关"
      selector:
        entity:
          domain: switch
    xiaoai_speaker:
      name: 小爱音箱
      description: "播报语音的媒体播放器"
      selector:
        entity:
          domain: media_player
    mesh_buttons:
      name: 随意贴
      description: "一个或多个随意贴按钮"
      selector:
        entity:
          domain: sensor
          multiple: true  # ✅ 关键修改：直接在 entity 下声明多选

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input door_sensor
    to: 'off'  # 门关闭

action:
  # 初始化临时状态
  - variables:
      waiting_for_button: true
      keep_power: false

  # 小爱音箱播报
  - service: media_player.play_media
    target:
      entity_id: !input xiaoai_speaker
    data:
      media_content_type: music
      media_content_id: "您好，您需要在1分钟内按下取点按钮保持空调不断电"

  # 等待随意贴按下或超时 1 分钟
  - wait_for_trigger:
      - platform: state
        entity_id: !input mesh_buttons
        to: 'on'
    timeout: '00:01:00'
    continue_on_timeout: true

  # 判断随意贴是否按下
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ waiting_for_button }}"
        sequence:
          - variables:
              keep_power: true

  # 空调控制逻辑（带二次门状态检查）
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ keep_power }}"
        sequence:
          - service: logbook.log
            data:
              name: "空调控制"
              message: "随意贴按下，保持供电，不断电"
      - conditions:
          - condition: template
            value_template: "{{ not keep_power and is_state(!input door_sensor, 'off') }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input air_conditioner
          - delay: '00:00:03'
          - service: switch.turn_on
            target:
              entity_id: !input air_conditioner

  # 清理临时状态
  - variables:
      waiting_for_button: false
      keep_power: false
