{\rtf1\ansi\ansicpg936\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset134 PingFangSC-Regular;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 blueprint:\
  name: "
\f1 \'c3\'f1\'cb\'de\'bd\'da\'b5\'e7\'c2\'df\'bc\'ad\'a3\'a8\'cd\'ea\'c8\'ab\'c1\'e3\'c5\'e4\'d6\'c3\'a3\'a9
\f0 "\
  description: "
\f1 \'c3\'c5\'b9\'d8\'b1\'d5\'b4\'a5\'b7\'a2\'bf\'d5\'b5\'f7\'d1\'d3\'ca\'b1\'a3\'ac\'cb\'e6\'d2\'e2\'cc\'f9\'bf\'c9\'b1\'a3\'b3\'d6\'b9\'a9\'b5\'e7\'a3\'ac\'c4\'da\'d6\'c3\'b6\'a8\'ca\'b1\'c6\'f7\'d3\'eb\'c1\'d9\'ca\'b1\'d7\'b4\'cc\'ac
\f0 "\
  domain: automation\
  input:\
    door_sensor:\
      name: 
\f1 \'c3\'c5\'b4\'c5
\f0 \
      description: "
\f1 \'c3\'c5\'b4\'c5\'b4\'ab\'b8\'d0\'c6\'f7
\f0 "\
      selector:\
        entity:\
          domain: binary_sensor\
    air_conditioner:\
      name: 
\f1 \'d6\'c7\'c4\'dc\'bf\'aa\'b9\'d8\'a3\'a8\'bf\'d5\'b5\'f7\'a3\'a9
\f0 \
      description: "
\f1 \'bf\'d8\'d6\'c6\'bf\'d5\'b5\'f7\'b5\'c4\'bf\'aa\'b9\'d8
\f0 "\
      selector:\
        entity:\
          domain: switch\
    xiaoai_speaker:\
      name: 
\f1 \'d0\'a1\'b0\'ae\'d2\'f4\'cf\'e4
\f0 \
      description: "
\f1 \'b2\'a5\'b1\'a8\'d3\'ef\'d2\'f4\'b5\'c4\'c3\'bd\'cc\'e5\'b2\'a5\'b7\'c5\'c6\'f7
\f0 "\
      selector:\
        entity:\
          domain: media_player\
    mesh_buttons:\
      name: 
\f1 \'cb\'e6\'d2\'e2\'cc\'f9
\f0 \
      description: "
\f1 \'d2\'bb\'b8\'f6\'bb\'f2\'b6\'e0\'b8\'f6\'cb\'e6\'d2\'e2\'cc\'f9\'b0\'b4\'c5\'a5
\f0 "\
      selector:\
        target:\
          entity:\
            domain: sensor\
            multiple: true\
\
variables:\
  waiting_for_button: "\{\{ state_attr('automation.' ~ automation.id, 'waiting_for_button') | default(false) \}\}"\
  keep_power: "\{\{ state_attr('automation.' ~ automation.id, 'keep_power') | default(false) \}\}"\
\
mode: single\
max_exceeded: silent\
\
trigger:\
  - platform: state\
    entity_id: !input door_sensor\
    to: 'off'   # 
\f1 \'c3\'c5\'b9\'d8\'b1\'d5
\f0 \
\
action:\
  # 1. 
\f1 \'b3\'f5\'ca\'bc\'bb\'af\'c1\'d9\'ca\'b1\'d7\'b4\'cc\'ac\'a3\'a8\'c4\'da\'d6\'c3\'a3\'a9
\f0 \
  - variables:\
      waiting_for_button: true\
      keep_power: false\
\
  # 2. 
\f1 \'b2\'a5\'b1\'a8\'cc\'e1\'ca\'be
\f0 \
  - service: media_player.play_media\
    target:\
      entity_id: !input xiaoai_speaker\
    data:\
      media_content_type: 'music'\
      media_content_id: "
\f1 \'c4\'fa\'ba\'c3\'a3\'ac\'c4\'fa\'d0\'e8\'d2\'aa\'d4\'da
\f0 1
\f1 \'b7\'d6\'d6\'d3\'c4\'da\'b0\'b4\'cf\'c2\'c8\'a1\'b5\'e3\'b0\'b4\'c5\'a5\'b1\'a3\'b3\'d6\'bf\'d5\'b5\'f7\'b2\'bb\'b6\'cf\'b5\'e7
\f0 "\
\
  # 3. 
\f1 \'b5\'c8\'b4\'fd\'cb\'e6\'d2\'e2\'cc\'f9\'b0\'b4\'cf\'c2\'bb\'f2\'b3\'ac\'ca\'b1
\f0  1 
\f1 \'b7\'d6\'d6\'d3
\f0 \
  - wait_for_trigger:\
      - platform: state\
        entity_id: !input mesh_buttons\
        to: 'on'\
    timeout: '00:01:00'\
    continue_on_timeout: true\
  - choose:\
      - conditions:\
          - condition: template\
            value_template: "\{\{ waiting_for_button \}\}"\
        sequence:\
          - variables:\
              keep_power: "\{\{ true \}\}"\
\
  # 4. 
\f1 \'c5\'d0\'b6\'cf\'bf\'d5\'b5\'f7\'bf\'d8\'d6\'c6\'c2\'df\'bc\'ad\'a3\'a8\'b4\'f8\'c3\'c5\'d7\'b4\'cc\'ac\'b6\'fe\'b4\'ce\'bc\'ec\'b2\'e9\'a3\'a9
\f0 \
  - choose:\
      - conditions:\
          - condition: template\
            value_template: "\{\{ keep_power \}\}"\
        sequence:\
          - service: logbook.log\
            data:\
              name: "
\f1 \'bf\'d5\'b5\'f7\'bf\'d8\'d6\'c6
\f0 "\
              message: "
\f1 \'cb\'e6\'d2\'e2\'cc\'f9\'b0\'b4\'cf\'c2\'a3\'ac\'b1\'a3\'b3\'d6\'b9\'a9\'b5\'e7\'a3\'ac\'b2\'bb\'b6\'cf\'b5\'e7
\f0 "\
      - conditions:\
          - condition: template\
            value_template: "\{\{ not keep_power and is_state(!input door_sensor, 'off') \}\}"\
        sequence:\
          - service: switch.turn_off\
            target:\
              entity_id: !input air_conditioner\
          - delay: '00:00:03'\
          - service: switch.turn_on\
            target:\
              entity_id: !input air_conditioner\
\
  # 5. 
\f1 \'c7\'e5\'c0\'ed\'c1\'d9\'ca\'b1\'d7\'b4\'cc\'ac
\f0 \
  - variables:\
      waiting_for_button: false\
      keep_power: false\
}